databases:
  - name: anv-db
    databaseName: anv_billing
    user: anv_user
    plan: free

services:
  - type: web
    name: anv-billing
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate && python manage.py setup_company 'ANV' --username admin --password admin1234"
    startCommand: "gunicorn anv_billing.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 60"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: anv-db
          property: connectionString
