# Generated by Django 5.2.13 on 2026-04-22 13:03

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='会社名')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '会社',
                'verbose_name_plural': '会社',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='会社名')),
                ('store_name', models.CharField(blank=True, max_length=200, verbose_name='稼働店舗名')),
                ('contact_name', models.CharField(blank=True, max_length=100, verbose_name='担当者名')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='請求書送付先メール')),
                ('daily_rate', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='受け単価（日当）')),
                ('payment_terms', models.CharField(blank=True, max_length=100, verbose_name='支払いサイト')),
                ('invoice_method', models.CharField(choices=[('email', 'メール'), ('mail', '郵送')], default='email', max_length=10, verbose_name='請求書送付方法')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.company')),
            ],
            options={
                'verbose_name': 'クライアント先',
                'verbose_name_plural': 'クライアント先',
                'ordering': ['name', 'store_name'],
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='会社名（請求書表示用）')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='郵便番号')),
                ('address', models.TextField(blank=True, verbose_name='住所')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='銀行名')),
                ('branch_name', models.CharField(blank=True, max_length=100, verbose_name='支店名')),
                ('account_type', models.CharField(choices=[('futsu', '普通'), ('toza', '当座')], default='futsu', max_length=10, verbose_name='口座種別')),
                ('account_number', models.CharField(blank=True, max_length=20, verbose_name='口座番号')),
                ('account_holder', models.CharField(blank=True, max_length=100, verbose_name='口座名義')),
                ('invoice_footer_notes', models.TextField(blank=True, verbose_name='請求書備考')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.company')),
            ],
            options={
                'verbose_name': '会社設定',
                'verbose_name_plural': '会社設定',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='会社名')),
                ('contact_name', models.CharField(blank=True, max_length=100, verbose_name='担当者名')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='銀行名')),
                ('branch_name', models.CharField(blank=True, max_length=100, verbose_name='支店名')),
                ('account_type', models.CharField(choices=[('futsu', '普通'), ('toza', '当座')], default='futsu', max_length=10, verbose_name='口座種別')),
                ('account_number', models.CharField(blank=True, max_length=20, verbose_name='口座番号')),
                ('account_holder', models.CharField(blank=True, max_length=100, verbose_name='口座名義')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='core.company')),
            ],
            options={
                'verbose_name': 'パートナー企業',
                'verbose_name_plural': 'パートナー企業',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', '管理者'), ('staff', 'スタッフ')], default='staff', max_length=10, verbose_name='権限')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ユーザープロフィール',
                'verbose_name_plural': 'ユーザープロフィール',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('daily_rate', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='パートナー単価（日当）')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='core.company')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='core.partner', verbose_name='所属パートナー企業')),
            ],
            options={
                'verbose_name': '稼働者',
                'verbose_name_plural': '稼働者',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_year', models.IntegerField(verbose_name='対象年')),
                ('target_month', models.IntegerField(verbose_name='対象月')),
                ('store_name', models.CharField(blank=True, max_length=200, verbose_name='稼働店舗')),
                ('days_worked', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='出勤数')),
                ('transport_cost', models.DecimalField(decimal_places=0, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='交通費')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('status', models.CharField(choices=[('pending', '未対応'), ('early_sent', '月初請求書 送付済'), ('late_sent', '月末請求書 送付済'), ('waiting_transfer', '振込待ち'), ('transferred', '振込完了')], default='pending', max_length=20, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_records', to='core.client', verbose_name='クライアント先')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_records', to='core.company')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_records', to='core.worker', verbose_name='稼働者')),
            ],
            options={
                'verbose_name': '稼働記録',
                'verbose_name_plural': '稼働記録',
                'ordering': ['-target_year', '-target_month', 'client__name'],
            },
        ),
    ]
